import type { Env } from '../types';
export type TaskType='script'|'analysis'|'creative'|'multimodal'|'bulk';
const models={workersFast:'@cf/meta/llama-3.1-8b-instruct-fast',workersQuality:'@cf/meta/llama-3.3-70b-instruct-fp8-fast',groqFast:'llama-3.1-8b-instant',groqQuality:'llama-3.3-70b-versatile',groqCreative:'meta-llama/llama-4-scout-17b-16e-instruct',gemini:'gemini-2.0-flash'};
export async function routeAI(env:Env,task:TaskType,prompt:string,systemPrompt=''):Promise<string>{ const today=new Date().toISOString().slice(0,10); const used=Number(await env.KV.get(`neurons:${today}`)||0); if(task!=='analysis'&&used>=8000&&env.GROQ_API_KEY) return groq(env,prompt,systemPrompt,models.groqFast); try { if(task==='multimodal'&&env.GEMINI_API_KEY) return gemini(env,prompt,systemPrompt); if((task==='creative'||task==='bulk')&&env.GROQ_API_KEY) return groq(env,prompt,systemPrompt,task==='creative'?models.groqCreative:models.groqFast); return workers(env,prompt,systemPrompt,task==='analysis'?models.workersQuality:models.workersFast); } catch { if(env.GROQ_API_KEY) return groq(env,prompt,systemPrompt,models.groqQuality); if(env.GEMINI_API_KEY) return gemini(env,prompt,systemPrompt); throw new Error('No AI provider is available'); } }
async function workers(env:Env,prompt:string,system:string,model:string){const result=await env.AI.run(model,{messages:[...(system?[{role:'system',content:system}]:[]),{role:'user',content:prompt}],max_tokens:1400,temperature:.7}) as {response?:string}; const day=new Date().toISOString().slice(0,10); const key=`neurons:${day}`; await env.KV.put(key,String(Number(await env.KV.get(key)||0)+100),{expirationTtl:90000}); if(!result.response) throw new Error('Workers AI returned no response'); return result.response;}
async function groq(env:Env,prompt:string,system:string,model:string){const res=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[...(system?[{role:'system',content:system}]:[]),{role:'user',content:prompt}],temperature:.7,max_tokens:1400})}); if(!res.ok) throw new Error(`Groq request failed: ${res.status}`); const data=await res.json() as {choices?:{message?:{content?:string}}[]}; const content=data.choices?.[0]?.message?.content; if(!content) throw new Error('Groq returned no content'); return content;}
async function gemini(env:Env,prompt:string,system:string){const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${models.gemini}:generateContent?key=${env.GEMINI_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:system?`${system}

${prompt}`:prompt}]}]})}); if(!res.ok) throw new Error(`Gemini request failed: ${res.status}`); const data=await res.json() as {candidates?:{content?:{parts?:{text?:string}[]}}[]}; const text=data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join(''); if(!text) throw new Error('Gemini returned no content'); return text;}
